export const FETCH_PLAYERS_SUCCESS = 'FETCH_PLAYERS_SUCCESS';
export const DELETE_PLAYER_SUCCESS = 'DELETE_PLAYER_SUCCESS';
export const ADD_PLAYER_SUCCESS = 'ADD_PLAYER_SUCCESS';
export const UPDATE_PLAYER_SUCCESS = 'UPDATE_PLAYER_SUCCESS';
export const TOGGLE_ADD_MODAL = 'OPEN_MODAL';
export const HANDLE_INPUT_CHANGE = 'HANDLE_INPUT_CHANGE';
